name: DAST Scan with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.TOKEN1 }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          

      # - name: Upload Scan Report as Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ZAP-Scan-Report
      #     path: |
      #       **/zap_report.html
      #       **/zap_report.md