name: DAST Scan with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://35.182.3.130' # Target the application container on the GitHub runner's localhost
          allow_issue_writing: false
          

      - name: Upload Scan Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Scan-Report
          path: |
            **/zap_report.html
            **/zap_report.md